### ISSUE TITLE
Align table with empty lines in EXAMPLES not working as it should

### ISSUE THREAD

**Issue by ismailktami** [alan-cole/vs-code-table-align#7]
Hello,
Can I have the possibility to align a table with empty rows?
In outline scenarios, when there are empty rows the table alignment does not work as it should.
 
Before Align
| user_role                            | setup | component_name                 | component_selector                                | expected_state |
| ADMIN     |       | add a new delivery mode button | [data-testid='add-delivery-mode-button']          | enabled     |

| RESTREINT |       | update delivery mode button    | [data-testid^='secured-button-on-update-details'] | disabled    |

After Align
Just the first line that will be aligned

Thanks in advance,

**Comment by alan-cole** [comment]
Thanks for the request. I've added a setting in 1.1.0 to allow tables to align with empty rows, this should be in settings:

![Screenshot_20241020_010948](https://github.com/user-attachments/assets/03f109e7-1648-48ec-a002-f7513ce42a57)
